[package]

name = "url"
# When updating version, also modify html_root_url in the lib.rs
version = "2.2.2"
authors = ["The rust-url developers"]

description = "URL library for Rust, based on the WHATWG URL Standard"
documentation = "https://docs.rs/url"
repository = "https://github.com/servo/rust-url"
readme = "../README.md"
keywords = ["url", "parser"]
categories = ["parser-implementations", "web-programming", "encoding"]
license = "MIT OR Apache-2.0"
include = ["src/**/*", "LICENSE-*", "README.md", "tests/**"]
edition = "2018"
rust-version = "1.45"

[badges]
travis-ci = { repository = "servo/rust-url" }
appveyor = { repository = "Manishearth/rust-url" }

[build-dependencies]
rustc_version = "0.4"

[dev-dependencies]
serde_json = "1.0"
bencher = "0.1"
# To test debugger visualizers defined for the url crate such as url.natvis
debugger_test = "0.1"
debugger_test_parser = "0.1"

[dependencies]
form_urlencoded = { version = "1.0.0", path = "../form_urlencoded" }
idna = { version = "0.2.0", path = "../idna", optional = true }
percent-encoding = { version = "2.1.0", path = "../percent_encoding" }
serde = {version = "1.0", optional = true, features = ["derive"]}

[features]
default = ["idna"]
# Enable to use the #[debugger_visualizer] attribute.

[[bench]]
name = "parse_url"
path = "benches/parse_url.rs"
harness = false

[[test]]
name = "debugger_visualizer"
path = "tests/debugger_visualizer.rs"
test = false
